export const urlKeys = {
    login: '/login',
    createUser: '/users',
    editUser: '/users',
    getUsers: '/users',
    createProject: '/projects',
    projects: '/projects',
    getUserById: '/users',
    logout: '/logout',
    hours: '/hours',
    completeProject: '/projects/',
    emailValidation: '/invites/validate',
    inviteRegister: '/invites/register',
    invites: '/invites',
    credentialsValidation: '/credentials/validation',
};
export const queryKeys = {
    customer: 'All Customers',
    employee: 'All Employees',
    active: 'Active',
    inactive: 'Inactive',
    users: 'Users',
    projects: 'Projects',
    user: 'User',
    hours: 'Hours',
    isValidEmail: 'IsValidEmail',
    pdf: 'PDF',
};
